ALTER TABLE users
DROP COLUMN IF EXISTS name,
ADD COLUMN first_name VARCHAR(100) NOT NULL,
ADD COLUMN last_name VARCHAR(100) NOT NULL,
ADD COLUMN mobile_number VARCHAR(20),
ADD COLUMN password_hash VARCHAR(255) NOT NULL,
ADD COLUMN last_login TIMESTAMP WITH TIME ZONE,
ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN is_active BOOLEAN DEFAULT TRUE;

UPDATE users
SET last_login = NOW()
WHERE last_login IS NULL;