ALTER TABLE users
DROP COLUMN IF EXISTS first_name,
DROP COLUMN IF EXISTS last_name,
DROP COLUMN IF EXISTS mobile_number,
DROP COLUMN IF EXISTS password_hash,
DROP COLUMN IF EXISTS last_login,
DROP COLUMN IF EXISTS updated_at,
DROP COLUMN IF EXISTS is_active,
ADD COLUMN name VARCHAR(255) NOT NULL;